import { ArchitectureModel, Component, Dependency, TargetArchitectureLayer } from '../types/architecture';

function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, '_');
}

export function generateMermaidDiagram(
  model: ArchitectureModel,
  mode: 'as-is' | 'to-be' = 'to-be'
): string {
  const lines: string[] = [];
  lines.push('flowchart TD');
  lines.push('  %% Generated by QuantumLens: Architecture Recovery');
  lines.push('  %% Model: ' + model.name);
  lines.push('');

  const nodeMap = new Map<string, Component>();
  for (const c of model.components) {
    nodeMap.set(c.id, c);
  }

  if (mode === 'to-be') {
    lines.push('  %% ================= PROPOSED TARGET ARCHITECTURE =================');
    const layers: { key: string; title: string; filter: (c: Component) => boolean }[] = [
      { key: 'apps', title: 'Layer 5: Applications & API Interfaces', filter: (c) => c.layer === 'apps' || c.type === 'app' },
      { key: 'reporting', title: 'Layer 4: BI & Analytics Consumption', filter: (c) => c.layer === 'reporting' || c.type === 'report' },
      { key: 'curated', title: 'Layer 3: Core Conformed Marts & Star Schemas', filter: (c) => c.layer === 'curated' },
      { key: 'staging', title: 'Layer 2: Staging & Data Cleansing', filter: (c) => c.layer === 'staging' },
      { key: 'source', title: 'Layer 1: Ingestion & Raw Lake', filter: (c) => c.layer === 'source' },
    ];

    for (const layer of layers) {
      const comps = model.components.filter(layer.filter);
      if (comps.length > 0) {
        lines.push(`  subgraph ${sanitizeId(layer.key)}["${layer.title}"]`);
        for (const c of comps) {
          const sId = sanitizeId(c.id);
          const icon = c.type === 'job' ? '⚙️ ' : c.type === 'report' ? '📊 ' : c.type === 'app' ? '📱 ' : '🗄️ ';
          lines.push(`    ${sId}["${icon}${c.name}"]`);
        }
        lines.push('  end');
        lines.push('');
      }
    }
  } else {
    lines.push('  %% ================= AS-IS LEGACY SYSTEM =================');
    // Group by component type in As-Is legacy layout
    const types: { key: string; title: string }[] = [
      { key: 'apps', title: 'Client Applications' },
      { key: 'reports', title: 'Legacy BI Reports' },
      { key: 'jobs', title: 'ETL Pipelines & Cron Scripts' },
      { key: 'tables', title: 'Database Tables & Views' },
    ];

    for (const t of types) {
      const comps = model.components.filter((c) => {
        if (t.key === 'apps') return c.type === 'app';
        if (t.key === 'reports') return c.type === 'report';
        if (t.key === 'jobs') return c.type === 'job';
        return c.type === 'table' || c.type === 'view';
      });

      if (comps.length > 0) {
        lines.push(`  subgraph ${t.key}["${t.title}"]`);
        for (const c of comps) {
          const sId = sanitizeId(c.id);
          const icon = c.type === 'job' ? '⚙️ ' : c.type === 'report' ? '📊 ' : c.type === 'app' ? '📱 ' : '🗄️ ';
          const alert = c.isUnusedCandidate ? ' ⚠️ [Unused]' : c.isDuplicateCandidate ? ' ⚠️ [Duplicate]' : '';
          lines.push(`    ${sId}["${icon}${c.name}${alert}"]`);
        }
        lines.push('  end');
        lines.push('');
      }
    }
  }

  lines.push('  %% Dependencies & Data Flow');
  for (const dep of model.dependencies) {
    const sId = sanitizeId(dep.source);
    const tId = sanitizeId(dep.target);
    const label = dep.needsReview ? `|needs review (${Math.round(dep.confidence * 100)}%)|` : `|${Math.round(dep.confidence * 100)}%|`;
    
    if (dep.needsReview) {
      lines.push(`  ${sId} -.->${label} ${tId}`);
    } else {
      lines.push(`  ${sId} -->${label} ${tId}`);
    }
  }

  lines.push('');
  lines.push('  %% Styles');
  lines.push('  classDef default fill:#f8fafc,stroke:#94a3b8,stroke-width:1.5px,color:#1e293b;');
  lines.push('  classDef reviewStyle fill:#fffbeb,stroke:#f59e0b,stroke-width:2px,stroke-dasharray: 4 4;');

  return lines.join('\n');
}
